import React from 'react'
import { monumentExtended } from "@/shared/fontLoader";
import Image from 'next/image'
import Collect1 from 'public/Magdiel-Lopez-15.png'
import Collect2 from 'public/Magdiel-Lopez-17.png'
import Collect3 from 'public/Magdiel-Lopez-18.png'
import "../globals.css";
// import Ecp from 'public/Ellipse 4.png'

const Collectibles = () => {
  return (
    <section className='mx-auto py-[100px] relative'>
      <div className='hidden xl:block glow'></div>
      <div className='hidden xl:block glow2'></div>
      {/* <Image
        className='absolute hidden xl:block right-[-10px]'
        src={Ecp}
        alt='Ellipse' /> */}
      <div className='text-white md:text-center font-thin mb-[119px]'>
        <h2 className={`${monumentExtended.className} tracking-[-0.04] lg:text-[40px] md:text-[30px] xs:px-5 md:px-[50px] xl:px-[311px]`}>A new wave of collectibles is about to hit the blockchain.</h2>
        <p className='xl:px-[322px] md:px-[100px] md:text-[13px] lg:text-lg mt-4 tracking-[-0.04] xs:px-5'>Characterised by soft lighting, vintage colour schemes and quirky costumes, these generative 3D TinyFaces are the addition to your NFT collection you’ve been waiting for.</p>
      </div>

      <div className='w-11/12 mx-auto'>
        <div className='flex items-center justify-center xl:flex-row xs:flex-col text-left text-white gap-[31px] mb-[100px]'>
          <Image
            src={Collect1}
            alt="Collect1"
          />
          <div className='md:w-[507px] border-solid border-[1px] rounded-lg px-4 py-[28.5px] xl:gap-12'>
            <h2 className={`${monumentExtended.className} xl:text-[64px] xs:text-[18px] font-black tracking-[-.08em] text-brightPink leading-[77px] xl:mb-14`}>Thousands of unique NFTs</h2>
            <p className='text-[24px] font-thin'>Each character is entirely unique and is generated by combining attributes such as colour palettes, skin tones, facial traits, outfits and accessories. With nearly endless combinations, all characters are guaranteed to be one of a kind.</p>
          </div>
        </div>
        <div className='flex items-center justify-center xl:flex-row xs:flex-col text-left text-white  gap-[31px]'>
          <div className='md:w-[507px] border-solid border-[1px] rounded-lg px-4 py-[28.5px] flex items-stretch flex-col xl:gap-[4.5rem]  '>
            <h2 className={`${monumentExtended.className} xl:text-[64px] xs:text-[20px] font-black tracking-[-.08em] text-brightPink xl:mb-16 leading-[77px]`}>Secure the most rare</h2>
            <p className='text-[24px] font-thin'>Even though no two Tinyfaces will ever be the same, some variations are rarer than others. Watch out for special accessories and raw materials - the rarer the attributes, the rarer your character will be.</p>
          </div>
          <div>
            <Image
              src={Collect2}
              alt="Collect2"
            />
          </div>
        </div>
        <div className='flex items-center justify-center xl:flex-row xs:flex-col text-left text-white  gap-[31px] mt-[100px]'>
          <Image
            src={Collect3}
            alt="Collect3"
          />
          <div className='md:w-[507px] border-solid border-[1px] rounded-lg px-4 py-[28.5px] xl:gap-12'>
            <h2 className={`${monumentExtended.className} xl:text-[64px] xs:text-[20px] font-black tracking-[-.09em] text-brightPink leading-[77px] xl:mb-14`}>Our  <br className='hidden xl:block' /> Environm<br className='hidden xl:block' />ent matter</h2>
            <p className='text-[24px] font-thin'>In order to enable our community to spend as little as possible in gas fees when minting, we opted for a contract made by Azuki called ERC721A, which allows minting multiple NFTs for essentially the same cost as minting a single one.</p>
          </div>
        </div>
      </div>
    </section>
  )
}

export default Collectibles;